import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,CalendarDays,ChartNoAxesCombined,UserRound,ChevronLeft,ChevronRight,Check,Plus,Minus,Timer,RotateCcw,Download,Upload,Dumbbell,ArrowUpRight,Flame,Droplets,Moon,Utensils,Play,Square} from 'lucide-react';
import {KEY,load,validate,localDate,dayFor,shiftDate,workout,workouts,mean7,fresh,type State,type Log,shiftForDate,dateTimeline} from './domain';
import './style.css';
const initial=load({getItem:key=>window.localStorage.getItem(key)});
function NumberField({value,onSave,min,max,label,placeholder='—'}:{value:number|undefined;onSave:(n:number|undefined)=>void;min:number;max:number;label:string;placeholder?:string}){
 const [draft,setDraft]=useState(value===undefined?'':String(value));const [invalid,setInvalid]=useState(false);
 useEffect(()=>{setDraft(value===undefined?'':String(value));setInvalid(false);},[value]);
 return <input aria-label={label} aria-invalid={invalid} title={invalid?`请输入 ${min}–${max} 之间的数值`:label} type="number" inputMode="decimal" min={min} max={max} step="0.1" value={draft} placeholder={placeholder} onChange={e=>{const v=e.target.value;setDraft(v);const n=Number(v);const valid=v===''||(Number.isFinite(n)&&n>=min&&n<=max);setInvalid(!valid);if(valid)onSave(v===''?undefined:n);}} onBlur={()=>{if(invalid){setDraft(value===undefined?'':String(value));setInvalid(false);}}}/>;
}
function App(){
 const [state,setState]=useState(initial.state),[error,setError]=useState(initial.error),[blocked,setBlocked]=useState(!!initial.error),[tab,setTab]=useState('今日'),[date,setDate]=useState(localDate()),[now,setNow]=useState(Date.now()),[toast,setToast]=useState(''),[pending,setPending]=useState<State|null>(null);
 const file=useRef<HTMLInputElement>(null);const day=dayFor(date,state.start),w=workout(day),log=state.logs[date]||{},wi=day===22?7:(day-1)%7;
 const update=(partial:Partial<State>)=>setState(s=>({...s,...partial}));
 const updateLog=(partial:Partial<Log>)=>setState(s=>({...s,logs:{...s.logs,[date]:{...s.logs[date],...partial}}}));
 useEffect(()=>{if(blocked)return;try{localStorage.setItem(KEY,JSON.stringify(state));setError('');}catch{setError('无法保存到本机，可能存储已满。请导出备份。');}},[state,blocked]);
 useEffect(()=>{if(!state.timerEnd)return;setNow(Date.now());if(state.timerEnd<=Date.now())return;const i=setInterval(()=>{const time=Date.now();setNow(time);if(time>=state.timerEnd!)clearInterval(i);},1000);return()=>clearInterval(i);},[state.timerEnd]);
 useEffect(()=>{if(!toast)return;const i=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(i);},[toast]);
 const remaining=state.timerEnd?Math.max(0,Math.ceil((state.timerEnd-now)/1000)):0;
 const total=w.ex.reduce((sum,e,i)=>sum+(state.targets[`${wi}-${i}`]||e.sets),0);
 const done=w.ex.reduce((sum,e,i)=>sum+Array.from({length:state.targets[`${wi}-${i}`]||e.sets},(_,j)=>log.sets?.[`${day}-${i}-${j}`]?.done?1:0).reduce<number>((a,b)=>a+b,0),0);
 const shift=shiftForDate(date,state.shiftStart,state.shiftEnd),timeline=dateTimeline(shift);const avg=mean7(state.logs,date);const points=Object.entries(state.logs).filter(([d,l])=>d<=date&&d>=shiftDate(date,-13)&&l.weight!==undefined).sort(([a],[b])=>a.localeCompare(b));
 const download=(raw=false)=>{try{const data=raw?localStorage.getItem(KEY)||'{}':JSON.stringify(state,null,2);const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`night-shift-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('备份已导出');}catch{setError('导出失败，请检查浏览器权限');}};
 const readFile=async(f?:File)=>{if(!f)return;try{if(f.size>5000000)throw Error('备份不能超过 5 MB');setPending(validate(JSON.parse(await f.text())));}catch(e){setError(e instanceof Error?e.message:'导入失败');}if(file.current)file.current.value='';};
 const metric=(key:'weight'|'waist'|'sleep'|'water',label:string,unit:string,min:number,max:number,Icon:typeof Moon)=><label className="metric"><span><Icon size={16}/>{label}</span><div><NumberField key={date+key} label={label} value={log[key]} min={min} max={max} onSave={n=>updateLog({[key]:n})}/><small>{unit}</small></div></label>;
 return <><div className="app"><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('今日');}}><img src="/icon-192.png" alt=""/>夜班训练<span>22</span></a><span className="local"><i/> 本机记录</span></header>
 {error&&<div className="error" role="alert">{error}{blocked&&<button onClick={()=>download(true)}>导出原始数据</button>}</div>}
 <main>
 <div className="page-heading"><div><p className="eyebrow">{tab==='今日'?'保持节奏，量力而行':tab==='计划'?'一个周期，逐日推进':tab==='记录'?'只看真实留下的数据':'属于你的训练节奏'}</p><h1>{tab==='今日'?'今天，练好这一组。':tab==='计划'?'22 天训练计划':tab==='记录'?'记录与变化':'个人与设置'}</h1></div><div className="day-badge"><strong>{String(day).padStart(2,'0')}</strong><span>/ 22 天</span></div></div>
 {tab!=='我的'&&<div className="date-bar"><button aria-label="前一天" onClick={()=>setDate(shiftDate(date,-1))}><ChevronLeft size={19}/></button><label><CalendarDays size={16}/><input aria-label="记录日期" type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><button aria-label="后一天" onClick={()=>setDate(shiftDate(date,1))}><ChevronRight size={19}/></button><button className="text-button" onClick={()=>setDate(localDate())}>今天</button></div>}
 {tab==='今日'&&<>
 <section className="workout-heading"><div><span className="tag">{day===22?'恢复日':`第 ${Math.ceil(day/7)} 轮`}</span><h2>{w.name}</h2><p>{w.hint}</p></div><div className="progress-ring" style={{background:`conic-gradient(var(--green) ${total?done/total*360:(wi===6?log.cardioDone:log.activity)?360:0}deg,#e5e9e6 0deg)`}}><div><strong>{total?`${done}/${total}`:(wi===6?log.cardioDone:log.activity)?'完成':'休整'}</strong><small>{total?'已完成组':'今日安排'}</small></div></div></section>
 {(date<state.start||date>shiftDate(state.start,21))&&<p className="notice">此日期在计划外，显示最近的计划日。可在「计划」调整开始日期。</p>}
 <div className="section-title"><h2>训练清单</h2><span>{total?`${w.ex.length} 个动作 · 重量 kg`:'恢复也是训练的一部分'}</span></div>
 {w.ex.map((ex,i)=><article className="exercise" key={`${day}-${i}`}><div className="exercise-title"><span className="exercise-number">{String(i+1).padStart(2,'0')}</span><div><h3>{ex.name}</h3><p>{ex.reps} 次 / 组</p></div><Dumbbell size={20}/></div><div className="set-header"><span>组</span><span>重量 · kg</span><span>次数</span><span>完成</span></div>{Array.from({length:state.targets[`${wi}-${i}`]||ex.sets},(_,j)=>{const k=`${day}-${i}-${j}`,entry=log.sets?.[k]||{weight:'',reps:'',done:false};const put=(p:Partial<typeof entry>)=>updateLog({sets:{...log.sets,[k]:{...entry,...p}}});return <div className={`set-row ${entry.done?'done':''}`} key={j}><span>{j+1}</span><input aria-label={`${ex.name} 第${j+1}组重量`} inputMode="decimal" placeholder="—" value={entry.weight} onChange={e=>/^\d{0,3}(\.\d{0,2})?$/.test(e.target.value)&&put({weight:e.target.value})}/><input aria-label={`${ex.name} 第${j+1}组次数`} inputMode="numeric" placeholder={ex.reps} value={entry.reps} onChange={e=>/^\d{0,3}$/.test(e.target.value)&&put({reps:e.target.value})}/><button title={entry.done?'撤销完成':'标记完成'} aria-label={`${ex.name} 第${j+1}组${entry.done?'撤销完成':'标记完成'}`} aria-pressed={entry.done} onClick={()=>put({done:!entry.done})}>{entry.done?<Check size={20}/>:<span className="empty-check"/>}</button></div>;})}</article>)}
 {!total&&wi!==6&&<section className="activity-section"><Activity size={34}/><h3>轻活动与恢复</h3><p>轻松散步，舒展肩背，保证充分睡眠。</p><button className={log.activity?'primary completed':'primary'} onClick={()=>updateLog({activity:!log.activity})}><Check size={18}/>{log.activity?'已完成 · 点击撤销':'记录完成'}</button></section>}
 {(total>0||wi===6)&&<section className="daily-cardio"><div className="section-title"><h2>{wi===6?'稳态有氧':'训练后有氧 · 可选'}</h2><span>{wi===0||wi===4?'参考 15–20 分钟':wi===1?'参考 20–25 分钟':wi===6?'按体感调整':'腿部训练日不作要求'}</span></div><div className="cardio-controls"><label><NumberField key={date+'cardio'} label="今日有氧分钟" min={0} max={180} value={log.cardioMinutes??(wi===0||wi===4?15:wi===1?20:wi===6?state.cardio:0)} onSave={n=>updateLog({cardioMinutes:n})}/><small>分钟</small></label><label className="cardio-check"><input type="checkbox" checked={!!log.cardioDone} onChange={e=>updateLog({cardioDone:e.target.checked})}/>有氧完成</label></div><p>快走、单车或椭圆机；疲劳时可跳过，不追求额外消耗。</p></section>}
 <section className="rest-bar"><Timer size={21}/><div><strong>组间休息</strong><span role="timer">{state.timerEnd?(remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'休息结束'): `${state.restSeconds} 秒`}</span></div><button aria-label="开始休息计时" title="开始 / 重新计时" onClick={()=>{setNow(Date.now());update({timerEnd:Date.now()+state.restSeconds*1000});}}><Play size={20}/></button><button aria-label="停止休息计时" title="停止计时" onClick={()=>update({timerEnd:null})}><Square size={17}/></button></section>
 <div className="section-title"><h2>身体与补给</h2><span>未填项不计入统计</span></div><div className="metrics">{metric('weight','体重','斤',40,600,Flame)}{metric('waist','腰围','cm',30,250,Activity)}{metric('sleep','睡眠','小时',0,24,Moon)}{metric('water','饮水','L',0,10,Droplets)}</div>
 <section className="meal-section"><h3><Utensils size={17}/>规律吃饭</h3><div className="meal-options">{['第一餐','第二餐','第三餐'].map((m,i)=><button aria-pressed={!!log.meals?.[i]} key={m} onClick={()=>{const meals=[...(log.meals||[false,false,false])];meals[i]=!meals[i];updateLog({meals});}} className={log.meals?.[i]?'selected':''}><Check size={17}/>{m}</button>)}</div><p>按起床后的顺序记录，不受夜班作息影响。</p></section>
 <section className="daily-timeline"><div className="section-title"><h2>{shift==='night'?'夜班':'白班'}作息参考</h2><span>{shift==='night'?'固定一次性班次':'非夜班日'}</span></div>{timeline.map(({time,label,optional})=>[time,`${label}${optional?' · 可选':''}`] as const).map(([time,text])=><div className="timeline-row" key={time}><time>{time}</time><span>{text}</span></div>)}<p>碳水可以正常吃，不必因夜班或晚餐而刻意断碳。睡眠不足时优先恢复。</p></section>
 </>}
 {tab==='计划'&&<><section className="settings-row"><label htmlFor="start">计划开始日期</label><input id="start" type="date" value={state.start} onChange={e=>e.target.value&&update({start:e.target.value})}/></section><p className="notice">推 / 拉 / 腿 / 休 / 上 / 下 / 有氧，共 3 轮；第 22 天恢复。点击日期查看或补记，已有记录仍保留在原日期。</p><div className="plan-grid">{Array.from({length:22},(_,i)=><button key={i} className={date===shiftDate(state.start,i)?'active':''} onClick={()=>{setDate(shiftDate(state.start,i));setTab('今日');}}><span>DAY {String(i+1).padStart(2,'0')}</span><strong>{workout(i+1).short}</strong><small>{shiftDate(state.start,i).slice(5).replace('-','/')}</small></button>)}</div><div className="section-title"><h2>训练目标</h2><span>应用到后续每轮</span></div>{workouts.map((x,k)=>x.ex.length>0&&<section className="target-section" key={k}><h3>{x.name}</h3>{x.ex.map((ex,i)=><div className="target-row" key={i}><span>{ex.name}<small>{ex.reps} 次</small></span><div className="stepper"><button aria-label={`减少${ex.name}${k}目标组数`} disabled={(state.targets[`${k}-${i}`]||ex.sets)<=1} onClick={()=>update({targets:{...state.targets,[`${k}-${i}`]:(state.targets[`${k}-${i}`]||ex.sets)-1}})}><Minus size={16}/></button><strong>{state.targets[`${k}-${i}`]||ex.sets}<small> 组</small></strong><button aria-label={`增加${ex.name}${k}目标组数`} disabled={(state.targets[`${k}-${i}`]||ex.sets)>=8} onClick={()=>update({targets:{...state.targets,[`${k}-${i}`]:(state.targets[`${k}-${i}`]||ex.sets)+1}})}><Plus size={16}/></button></div></div>)}</section>)}<p className="notice">减少目标组数不会删除隐藏组的记录，增加回来仍可查看。</p></>}
 {tab==='记录'&&<><section className="summary"><div><span>近 7 日平均体重</span><strong>{avg.value===null?'—':avg.value.toFixed(1)}<small> 斤</small></strong><p>{avg.count?`${avg.count} 天实际记录 · 截至 ${date.slice(5)}`:'尚无体重记录，先记录今天的状态'}</p></div><ChartNoAxesCombined size={32}/></section><div className="section-title"><h2>体重趋势</h2><span>近 14 日 · 斤</span></div>{points.length>0?<section className="chart"><svg viewBox="0 0 600 200" role="img" aria-label="近14日体重趋势图">{(()=>{const values=points.map(([,l])=>l.weight!),min=Math.min(...values)-1,max=Math.max(...values)+1;const coords=points.map(([d,l])=>[35+(Date.parse(d+'T12:00:00Z')-Date.parse(shiftDate(date,-13)+'T12:00:00Z'))/86400000/13*525,160-(l.weight!-min)/(max-min)*125]);return <>{[min,(min+max)/2,max].map((v,i)=><g key={i}><line x1="35" x2="570" y1={160-i*62.5} y2={160-i*62.5} stroke="#e4e9e5"/><text x="0" y={164-i*62.5}>{v.toFixed(0)}</text></g>)}<polyline points={coords.map(p=>p.join(',')).join(' ')} fill="none" stroke="#228461" strokeWidth="3"/>{coords.map(([x,y],i)=><circle key={i} cx={x} cy={y} r="5" fill="#228461"><title>{points[i][0]}：{points[i][1].weight} 斤</title></circle>)}<text x="35" y="190">{shiftDate(date,-13).slice(5)}</text><text x="535" y="190">{date.slice(5)}</text></>;})()}</svg></section>:<section className="empty"><ChartNoAxesCombined size={35}/><h3>趋势，从第一次记录开始</h3><p>没有占位数据，体重将按实际日期展示。</p><button className="primary" onClick={()=>setTab('今日')}>去记录<ArrowUpRight size={17}/></button></section>}<div className="section-title"><h2>每日记录</h2><span>{Object.keys(state.logs).length} 天</span></div>{Object.keys(state.logs).length===0?<p className="notice">还没有记录。完成一组训练或填写身体数据后，会显示在这里。</p>:Object.entries(state.logs).sort(([a],[b])=>b.localeCompare(a)).map(([d,l])=><button key={d} className="history-row" onClick={()=>{setDate(d);setTab('今日');}}><div><strong>{d}</strong><span>{Object.values(l.sets||{}).filter(s=>s.done).length} 组完成{l.activity?' · 活动完成':''}</span></div><div><strong>{l.weight===undefined?'—':`${l.weight} 斤`}</strong><span>{l.sleep===undefined?'睡眠未记录':`睡眠 ${l.sleep} 小时`}</span></div><ChevronRight size={17}/></button>)}</>}
 {tab==='我的'&&<><section className="profile-banner"><div className="avatar"><UserRound size={29}/></div><div><h2>我的夜班节奏</h2><p>训练与生活，都按自己的步调。</p></div></section><div className="section-title"><h2>身体基线</h2><span>不计入每日体重</span></div>{(['height','weight'] as const).map(k=><label className="settings-row" key={k}><span>{k==='height'?'身高 · cm':'初始体重 · 斤'}</span><NumberField label={k==='height'?'身高':'初始体重'} value={state.profile[k]} min={k==='height'?100:40} max={k==='height'?250:600} onSave={n=>{if(n!==undefined)update({profile:{...state.profile,[k]:n}});}}/></label>)}<div className="section-title"><h2>本次班次</h2><span>只影响作息提示，不会自动换训练日</span></div><label className="settings-row"><span>夜班开始日期</span><input aria-label="夜班开始日期" type="date" value={state.shiftStart} onChange={e=>e.target.value&&update({shiftStart:e.target.value})}/></label><label className="settings-row"><span>夜班结束日期</span><input aria-label="夜班结束日期" type="date" value={state.shiftEnd} onChange={e=>e.target.value&&update({shiftEnd:e.target.value})}/></label><p className="notice">本次固定夜班日期为上述范围；白班工作时间 08:00–20:00。不是每月自动重复。</p><div className="section-title"><h2>训练偏好</h2></div><label className="settings-row"><span>组间休息</span><select aria-label="组间休息时长" value={state.restSeconds} onChange={e=>update({restSeconds:Number(e.target.value)})}>{[30,60,90,120,180,300].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label><label className="settings-row"><span>有氧时长 · 分钟</span><NumberField label="有氧时长" value={state.cardio} min={5} max={180} onSave={n=>{if(n!==undefined)update({cardio:n});}}/></label><div className="section-title"><h2>数据与备份</h2><span>仅保存在此浏览器</span></div><button className="action-row" onClick={()=>download()}><Download size={20}/><span>导出完整备份<small>JSON · 包含训练、身体记录和设置</small></span><ChevronRight size={18}/></button><button className="action-row" onClick={()=>file.current?.click()}><Upload size={20}/><span>导入备份<small>校验后确认，替换本机全部记录</small></span><ChevronRight size={18}/></button><input ref={file} className="hidden" type="file" accept=".json,application/json" onChange={e=>readFile(e.target.files?.[0])}/><button className="action-row danger" onClick={()=>{if(confirm('清空本机全部记录和设置？此操作不可撤销，请先导出备份。')){setBlocked(false);setState(fresh());setToast('已重置本机数据');}}}><RotateCcw size={19}/><span>重置本机数据</span></button><section className="privacy"><h3>数据留在你的设备上</h3><p>无账号、无上传。清理浏览器数据可能导致记录丢失，请定期备份。夜班后疲劳明显时适当减量；训练安排仅供参考，不是医疗建议。</p><h3>添加到 iPhone 主屏幕</h3><p>使用 Safari 打开 HTTPS 地址，轻点分享，再选择「添加到主屏幕」。首次联网加载后可离线使用。局域网 HTTP 仅供预览，不保证离线能力。</p></section></>}
 <footer>夜班训练 · 每一点真实进步都算数</footer></main></div>
 <nav className="bottom-nav" aria-label="主导航">{[['今日',Dumbbell],['计划',CalendarDays],['记录',ChartNoAxesCombined],['我的',UserRound]].map(([label,Icon])=>{const I=Icon as typeof Dumbbell;return <button key={label as string} className={tab===label?'active':''} aria-current={tab===label?'page':undefined} onClick={()=>{setTab(label as string);window.scrollTo(0,0);}}><I size={21}/><span>{label as string}</span></button>;})}</nav>
 {toast&&<div className="toast" role="status">{toast}</div>}
 {pending&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><h2 id="import-title">替换本机记录？</h2><p>备份包含 {Object.keys(pending.logs).length} 天记录。继续将覆盖全部现有数据，无法撤销。</p><div><button autoFocus onClick={()=>setPending(null)}>取消</button><button className="primary" onClick={()=>{setState(pending);setPending(null);setBlocked(false);setToast('备份已导入');}}>确认替换</button></div></section></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
if('serviceWorker' in navigator&&import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
